In [1]:
# import numpy
import numpy as np

In [2]:
# create array x
x = np.array(np.arange(12))

In [3]:
# print the shape of x
x.shape

(12,)

In [26]:
# create a two dimensional array
x_2d = np.array([[0, 0, 2, 3, 4, 5],[5, 4, 3, 2, 1, 0]])
x_2d

array([[0, 0, 2, 3, 4, 5],
       [5, 4, 3, 2, 1, 0]])

In [18]:
# print shape of 2d array
x_2d.shape

(2, 6)

In [19]:
# reshape the array to 2 x 6
x_2d.reshape(2,6)

array([[0, 1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1, 0]])

In [20]:
# reshape the array to 1 x 12
x_2d.reshape(1,12)

array([[0, 1, 2, 3, 4, 5, 5, 4, 3, 2, 1, 0]])

In [21]:
# transpose the array
x_2d.T

array([[0, 5],
       [1, 4],
       [2, 3],
       [3, 2],
       [4, 1],
       [5, 0]])

In [33]:
x_2d

array([[0, 0, 2, 3, 4, 5],
       [5, 4, 3, 2, 1, 0]])

In [32]:
# indexing method 1
x_2d[0][1]

0

In [27]:
# indexing method 2
x_2d.nonzero()

(array([0, 0, 0, 0, 1, 1, 1, 1, 1]), array([2, 3, 4, 5, 0, 1, 2, 3, 4]))

In [31]:
# indexing method 3
x_2d[0,1]

0

In [34]:
# indexing method 4
x_2d[1,-2]

1

In [35]:
# indexing method 5
x_2d[0,2:4]

array([2, 3])

In [36]:
# indexing method 6
x_2d[:,[2,4,5]]

array([[2, 4, 5],
       [3, 1, 0]])

In [57]:
x_2d

array([[0, 0, 2, 3, 4, 5],
       [5, 4, 3, 2, 1, 0]])

In [45]:
x_2d[:,x_2d[0,:] < 2]

array([[0, 0],
       [5, 4]])

In [42]:
x_2d[0,:] >2

array([False, False, False,  True,  True,  True], dtype=bool)

In [55]:
x_2d > 2

array([[False, False, False,  True,  True,  True],
       [ True,  True,  True, False, False, False]], dtype=bool)

In [56]:
x_2d[x_2d>2]

array([3, 4, 5, 5, 4, 3])